# Generated by Django 3.2.6 on 2021-10-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmoney_info',
            name='add_money',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], default='Income', max_length=10),
        ),
    ]
